name: progressive_background_blur
description: "Progressive background blur widget to create smooth layered frosted glass effect for Flutter."
version: 0.0.2
homepage: https://github.com/LeoLi-Byte
repository: https://github.com/LeoLi-Byte/progressive_background_blur
issue_tracker: https://github.com/LeoLi-Byte/progressive_background_blur/issues
topics:
  - progressive
  - progressive-blur
  - background-blur
  - shaders
  - figma

environment:
  sdk: ^3.11.0
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

flutter:
  # 片段着色器（Figma Effects -> Background blur -> Progressive）
  shaders:
    - lib/shaders/progressive_blur.frag
